try:
    pa
except Exception as e:
    print(e)